title: "Vereniging Open Nederland"
tagline: "verbinden van open"
open-definition: "Open data en content mag vrijelijk worden gebruikt, aangepast en gedeeld - door iedereen, voor ieder doel."
description: "Bevorderen van toegang tot informatie, kennis en cultuur"
twitter: "@OpenNederland"
social-image: header-banner-bijeenkomst-foto.jpg
icon: assets/img/ON-beeldmerk-2024.png

collections:
  tags:
    output: true
    permalink: /tags/:name/
  members:
    output: true
    permalink: /leden/:name/
  initiatives:
    output: true
    permalink: /initiatief/:name/
defaults:
  - scope:
      type: tags
    values:
      layout: tags
      collection: tags
  - scope:
      type: members
    values:
      layout: members
      collection: members
  - scope:
      type: initiatives
    values:
      layout: initiatives
      collection: initiatives